name: Deploy AWS

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > /home/runner/minhkakartwebserver.pem
          chmod 400 /home/runner/minhkakartwebserver.pem
          ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> /home/runner/.ssh/known_hosts
        
      - name: Connect to server using ssh
        run: |
          sudo ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i "/home/runner/minhkakartwebserver.pem" ubuntu@${{ secrets.AWS_SSH_HOST }} "echo Connected" "
            cd ~/dotnetprj/dotnet-simple-jwt-auth/;
            git pull;
            sudo docker stop baseauth;
            docker system prune -a --volumes -f;
            sudo docker build -f Dockerfile -t baseauth .;
            sudo docker run -p 8080:8080 --name baseauth baseauth || sudo docker restart baseauth;
            exit;
          "
      - name: Clean up
        run: rm -f /home/runner/minhkakartwebserver.pem