name: Deploy AWS

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN RSA PRIVATE KEY-----
            ${{ secrets.AWS_SSH_KEY }}
            -----END RSA PRIVATE KEY-----" > /tmp/temp_key.pem
          chmod 400 /tmp/temp_key.pem
          ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Connect to server using ssh
        run: ssh -T -i "/tmp/temp_key.pem" ${{ secrets.AWS_SSH_HOST }}
      - name: Accept for the first time
        run: echo "yes"
      - name: Deploy
        run: |
          cd /home/ubuntu/dotnetprj/dotnet-simple-jwt-auth/
          git pull
          sudo docker build -f Dockerfile -t baseauth .
          sudo docker restart baseauth
          sudo docker image prune -a -f
          sudo docker container prune -a -f
          logout
      - name: Clean up
        run: rm -f /tmp/temp_key.pem