name: Deploy AWS

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH key and known_hosts
        run: |
          sudo mkdir -p ~/.ssh
          sudo echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/minhkakartwebserver.pem
          sudo chmod 400 ~/.ssh/minhkakartwebserver.pem
          sudo ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Connect to server using ssh
        run: sudo ssh -i "~/.ssh/minhkakartwebserver.pem" ${{ secrets.AWS_SSH_HOST }} "echo Connected"
      - name: Accept for the first time
        run: echo "yes"
      - name: Deploy
        run: |
          cd /home/ubuntu/dotnetprj/dotnet-simple-jwt-auth/
          git pull
          sudo docker build -f Dockerfile -t baseauth .
          sudo docker restart baseauth
          sudo docker image prune -a -f
          sudo docker container prune -a -f
          logout
      - name: Clean up
        run: |
          rm -f /tmp/minhkakartwebserver.pem
          rm -f ~/.ssh/minhkakartwebserver.pem